### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
-

### CODE REVIEW

**Comment by dysk0** [comment]
It is too early for translations, but thanks :)

**Comment by Caballlero** [comment]
I know it is too early,but i am intereted in this  project.

**Comment by Caballlero** [comment]
dysk0 can you unpatch my file ,I did it wrong, I will send it to you again.

**Comment by dysk0** [comment]
You did it :)

**Comment by ghost** [comment]
I have translated many apps without any problems, which I did wrong in this case, it is gentleman you will notify me what was the error, because I do not understand. This would be part of my knowledge if you tell me the cause. Note: i am new of this and could make mistakes. We need talk to get a solution of this.

cheers.

**Comment by dysk0** [comment]
May I suggest you to use: https://www.transifex.com/dysko/tooter/ 
You were started to translate app to early, and a lot of translation strings were changed during development...

**Pull request merged**
